###########################################################################
#                              RasMol 2.7.0                               #  
#                                                                         #
#                                 RasMol                                  #
#                 Molecular Graphics Visualisation Tool                   #
#                             23 March 1999                               #
#                                                                         #
#                   Based on RasMol 2.6 by Roger Sayle                    #
# Biomolecular Structures Group, Glaxo Wellcome Research & Development,   #
#                      Stevenage, Hertfordshire, UK                       #
#         Version 2.6, August 1995, Version 2.6.4, December 1998          #
#                   Copyright (C) Roger Sayle 1992-1999                   #
#                                                                         #
#               Version 2.7.0 Mods by Herbert J. Bernstein                #
#           Bernstein + Sons, P.O. Box 177, Bellport, NY, USA             #
#                      yaya@bernstein-plus-sons.com                       #
#                               March 1999                                #
#              Copyright (C) Herbert J. Bernstein 1998-1999               #
#                                                                         #
# Please read the file NOTICE for important notices which apply to this   #
# package. If you are not going to make changes to RasMol, you are not    # 
# only permitted to freely make copies and distribute them, you are       # 
# encouraged to do so, provided you do the following:                     #
#   * 1. Either include the complete documentation, especially the file   #
#     NOTICE, with what you distribute or provide a clear indication      #
#     where people can get a copy of the documentation; and               #
#   * 2. Please give credit where credit is due citing the version and    # 
#     original authors properly; and                                      #  
#   * 3. Please do not give anyone the impression that the original       #   
#     authors are providing a warranty of any kind.                       #
#                                                                         #
# If you would like to use major pieces of RasMol in some other program,  #
# make modifications to RasMol, or in some other way make what a lawyer   #
# would call a "derived work", you are not only permitted to do so, you   #
# are encouraged to do so. In addition to the things we discussed above,  #
# please do the following:                                                #
#   * 4. Please explain in your documentation how what you did differs    #
#     from this version of RasMol; and                                    #
#   * 5. Please make your modified source code available.                 #
#                                                                         #
# This version of RasMol is not in the public domain, but it is given     #
# freely to the community in the hopes of advancing science. If you make  #
# changes, please make them in a responsible manner, and please offer us  #
# the opportunity to include those changes in future versions of RasMol.  #
###########################################################################
#
CC   = CL /nologo /J /W3
LD   = LINK /nologo /WARN:3 /SUBSYSTEM:windows /NODEFAULTLIB:oldnames.lib

DEBUG = 0

!if $(DEBUG)
CFLAGS = /Zi /Od
LFLAGS = /DEBUG /MAP:raswin.map
!else
.SILENT:

# 386 CPU or above:  /G3
# 486 CPU or above:  /G4
CFLAGS = /G4rs /O2gipab1
LFLAGS =
!endif

LIBS   = user32.lib gdi32.lib comdlg32.lib shell32.lib

OBJS   = raswin.obj molecule.obj command.obj abstree.obj transfor.obj \
	render.obj pixutils.obj mswin31.obj outfile.obj script.obj \
	cif_fract.obj cif.obj cif_ctonum.obj cif_stx.obj



goal:           raswin.exe

raswin.exe:     $(OBJS) raswin.def raswin.res
		$(LD) $(LFLAGS) $(OBJS) raswin.res $(LIBS) /OUT:raswin.exe

raswin.obj:     raswin.c rasmol.h raswin.idm molecule.h command.h \
		abstree.h transfor.h render.h pixutils.h graphics.h \
		outfile.h
		$(CC) /c $(CFLAGS) raswin.c

molecule.obj:   molecule.c molecule.h rasmol.h abstree.h command.h \
		transfor.h render.h
		$(CC) /c $(CFLAGS) molecule.c

transfor.obj:   transfor.c transfor.h rasmol.h molecule.h command.h \
		render.h graphics.h
		$(CC) /c $(CFLAGS) transfor.c

command.obj:    command.c command.h rasmol.h tokens.h abstree.h \
		molecule.h transfor.h render.h graphics.h pixutils.h \
		outfile.h
		$(CC) /c $(CFLAGS) command.c

abstree.obj:    abstree.c abstree.h rasmol.h molecule.h
		$(CC) /c $(CFLAGS) abstree.c

render.obj:     render.c render.h rasmol.h molecule.h transfor.h \
		command.h graphics.h pixutils.h
		$(CC) /c $(CFLAGS) render.c

mswin31.obj:    mswin31.c graphics.h rasmol.h render.h
		$(CC) /c $(CFLAGS) mswin31.c

pixutils.obj:   pixutils.c pixutils.h rasmol.h render.h graphics.h
		$(CC) /c $(CFLAGS) pixutils.c

outfile.obj:    outfile.c outfile.h rasmol.h command.h transfor.h \
		render.h graphics.h pixutils.h script.h
		$(CC) /c $(CFLAGS) outfile.c

script.obj:	script.c script.h rasmol.h command.h transfor.h \
		render.h graphics.h pixutils.h
		$(CC) /c $(CFLAGS) script.c

cif_fract.obj: cif_fract.c rasmol.h
		$(CC) /c $(CFLAGS) cif_fract.c

cif.obj:       cif.c, cif.h rasmol.h molecule.h
		$(CC) /c $(CFLAGS) cif.c

cif_ctonum.obj: cif_ctonum.c cif_ctonum.h rasmol.h
		$(CC) /c $(CFLAGS) cif_ctonum.c

cif_stx.obj:   cif_stx.c cif.h
		$(CC) /c $(CFLAGS) cif_stx.c

raswin.res:     raswin.rc raswin.idm
		$(RC) /fo raswin.res /r raswin.rc 
